### YamlMime:Landing
title: Azure Arc Kubernetes (förhandsversion)
summary: Läs mer om hur du hanterar Kubernetes-kluster med Azure Arc
metadata:
  title: Azure Arc Kubernetes
  description: Läs mer om hur du hanterar lokala datorer i Azure
  author: 
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 06/26/2020
  ms.author: 
  ms.openlocfilehash: 88d9ba51815496e7d8ec4ab3d22195c5b42c317b
  ms.sourcegitcommit: 86acfdc2020e44d121d498f0b1013c4c3903d3f3
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 12/17/2020
  ms.locfileid: "97616974"
landingContent:
- title: Anslut Kubernetes-kluster till Azure med Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: Vad är Azure Arc-aktiverade Kubernetes?
      url: overview.md
  - linkListType: quickstart
    links:
    - text: Jumpstart
      url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
    - text: Anslut kluster
      url: connect-cluster.md
  - linkListType: how-to-guide
    links:
    - text: Distribuera konfigurationer med GitOps
      url: use-gitops-connected-cluster.md
    - text: Distribuera Helm-diagram med GitOps
      url: use-gitops-with-helm.md
    - text: Framtvinga GitOps med hjälp av Azure Policy
      url: use-azure-policy.md
    - text: Distribuera Azure IoT Edge-arbetsbelastningar
      url: deploy-azure-iot-edge-workloads.md
- title: Referensarkitektur
  linkLists:
  - linkListType: architecture
    links:
    - text: Hantera distributioner och konfigurationer för Kubernetes-hybridkluster
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
