### YamlMime:Landing
title: Azure Arc Kubernetes (förhandsversion)
summary: Läs mer om hur du hanterar Kubernetes-kluster med Azure Arc
metadata:
  title: Azure Arc Kubernetes
  description: Läs mer om hur du hanterar lokala datorer i Azure
  author: 
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 06/26/2020
  ms.author: 
  ms.openlocfilehash: bc12e75904f375e2e40bce01d102186ec0d39f13
  ms.sourcegitcommit: 2c586a0fbec6968205f3dc2af20e89e01f1b74b5
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 10/14/2020
  ms.locfileid: "92014264"
landingContent:
- title: Anslut Kubernetes-kluster till Azure med Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: Vad är Azure Arc-aktiverade Kubernetes?
      url: overview.md
  - linkListType: quickstart
    links:
    - text: Anslut kluster
      url: connect-cluster.md
  - linkListType: how-to-guide
    links:
    - text: Distribuera konfigurationer med GitOps
      url: use-gitops-connected-cluster.md
    - text: Distribuera Helm-diagram med GitOps
      url: use-gitops-with-helm.md
    - text: Framtvinga GitOps med hjälp av Azure Policy
      url: use-azure-policy.md
    - text: Distribuera Azure IoT Edge-arbetsbelastningar
      url: deploy-azure-iot-edge-workloads.md
- title: Referensarkitektur
  linkLists:
  - linkListType: architecture
    links:
    - text: Hantera distributioner och konfigurationer för Kubernetes-hybridkluster
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
